-- Example reviewed write for a feature table in a work schema.
-- Replace WORK_SCHEMA, SOURCE_SCHEMA, table names, and score-date logic for your own project.

CREATE TABLE WORK_SCHEMA.CUSTOMER_CHURN_FEATURES AS
SELECT
    p.CUSTOMER_ID,
    p.SEGMENT_CODE,
    p.CUSTOMER_STATUS,
    MAX(CASE WHEN e.EVENT_TYPE = 'LOGIN' THEN e.EVENT_TS END) AS LAST_LOGIN_TS,
    COUNT(CASE WHEN e.EVENT_TYPE = 'ORDER' THEN 1 END) AS ORDERS_90D,
    SUM(CASE WHEN e.EVENT_TYPE = 'ORDER' THEN COALESCE(e.AMOUNT, 0) ELSE 0 END) AS REVENUE_90D,
    COUNT(CASE WHEN e.EVENT_TYPE = 'TICKET' THEN 1 END) AS SUPPORT_TICKETS_90D
FROM SOURCE_SCHEMA.CUSTOMER_PROFILE p
LEFT JOIN SOURCE_SCHEMA.CUSTOMER_EVENTS e
  ON p.CUSTOMER_ID = e.CUSTOMER_ID
 AND e.EVENT_TS >= ADD_DAYS(CURRENT_DATE, -90)
 AND e.EVENT_TS < CURRENT_DATE
GROUP BY
    p.CUSTOMER_ID,
    p.SEGMENT_CODE,
    p.CUSTOMER_STATUS;
